### ISSUE TITLE
Application preferences

### ISSUE THREAD

**Issue by stewartadam** [cbguder/FLAC2iTunes#1]
Thank you for writing this application, this saved me a bunch of time!

It would be really great if the application could have a preference dialog that allowed a configurable number of decode tasks and a configurable temporary directory. I am using the app on a SSD, so naturally I don't want to be decoding >= 20GB of WAV files to the default temporary directory which falls on the SSD.

**Comment by cbguder** [comment]
Thank you for your comments.

As you might have noticed, I haven't worked on this app for over a year now, and although I too could use these two features, I can't promise to implement them anytime soon. In the meantime, you might wanna take a look at [XLD](http://tmkk.undo.jp/xld/index_e.html).

**Comment by stewartadam** [comment]
Thanks! XLD looks good for my needs now.

If you ever get around to implementing this, I would be happy to donate a few dollars to help pay for the time... I would submit a patch myself if I could, but unfortunately I am not very familiar with Objective-C!

**Comment by cbguder** [comment]
Build 10 uses as many decode tasks as CPU cores. Temp directory is still not configurable.
