### ISSUE TITLE
Itunes Metadata

### ISSUE THREAD

**Issue by bookemdano08** [cbguder/FLAC2iTunes#2]
Hi cbguder,

Well given we're now in 2017 and OS X...err MacOS 10.12 I sort of expected this app to be broken (given how many changes Apple has made to iTunes over the years). But having just run a couple of albums through it it's working fine.

I'm super intrigued about the Fetch button, although I can find no documentation about it and it does appear to be broken (well, there's no error but it doesn't seem to do anything after pasting in a store URL). I know this app is basically abandoned, but can you tell me if this function ever was working, and if so, do you have any ideas about where it could be failing? Am I supposed to put in the store URL and then drag an album onto the main window? Or do I drag the album first and select the files, then enter the store URL? I've tried both already to no avail, but wondering how it was supposed to work.

I tagged all my FLACs with MusicBrainz metadata quite some time ago. But there are some things I don't like about its methodology and at this point I'd prefer to just standardize on the iTunes store data. Only problem has been finding a way to automate it. If I could get your app to do it for me while importing the FLACs that would be amazing... all that would be left would be to fetch the cover art from iTunes.

Even as-is this app is saving me time. I read on stackexchange you're using the Mastered for iTunes settings, which is what I wanted. Thank you!

**Comment by cbguder** [comment]
@bookemdano08 Hi! I'm glad to hear you find the app useful. Unfortunately, I no longer use or maintain it, but please feel free to fork it if you think you can fix the issue.

As for why it fails to fetch metadata, my best guess would be that Apple changed the format of iTunes album pages. The metadata fetcher scrapes iTunes web pages, so it was always an extremely fragile hack. I'm surprised it worked as long as it did. A better solution would be to use the iTunes API, but that was very poorly documented back when I wrote this app, and I'd be surprised if things were any better today.

How it's *supposed* to work is, you simply find the iTunes page for the album (I usually just Google <Album Name> site:itunes.apple.com) and paste the link into the text field. No need to select anything.
